<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página con Navbar</title>
    <link rel="stylesheet" href="styles.css">
</head>
<style>
    .terms-conditions {
        text-align: left;
        line-height: 1.6;
        margin: 20px;
        font-size: 16px;
        color: #333;
    }

    .v1 {
        font-weight: bold;
    }

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: Arial, sans-serif;
        line-height: 1.6;
    }

    header {
        background-color: #dc143c;
        color: #fff;
        padding: 10px 0;
    }

    .navbar {
        display: flex;
        flex-wrap: wrap;
        /* Permite que los elementos se envuelvan en pantallas pequeñas */
        justify-content: center;
        align-items: center;
        max-width: 1200px;
        margin: 0 auto;
        padding: 0 20px;
    }

    .logo {
        font-size: 24px;
        font-weight: bold;
    }

    .nav-links {
        list-style: none;
        display: flex;
        flex-wrap: wrap;
        /* Permite que los enlaces se envuelvan */
    }

    .nav-links li {
        margin-left: 20px;
    }

    .nav-links a {
        color: #fff;
        text-decoration: none;
        padding: 10px 15px;
        transition: background-color 0.3s;
    }

    .nav-links a:hover {
        background-color: #575757;
        border-radius: 4px;
    }

    main {
        padding: 20px;
        text-align: center;
    }

    .vista {
        display: none;
    }

    .vista h1 {
        font-size: 28px;
        margin-bottom: 10px;
    }

    .vista p {
        font-size: 18px;
    }

    .carrusel-container {
        position: relative;
        width: 100%;
        /* Cambiado a 100% para hacer la imagen responsiva */
        max-width: 300px;
        /* Ancho máximo para la imagen */
        height: 600px;
        /* Alto fijo */
        margin: 20px auto;
        overflow: hidden;
        border-radius: 10px;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
    }

    .carrusel {
        display: flex;
        transition: transform 0.5s ease-in-out;
        height: 100%;
    }

    .slide {
        min-width: 100%;
        /* Cada slide ocupa el 100% del contenedor */
        height: 100%;
    }

    .slide img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        border-radius: 10px;
    }

    .prev,
    .next {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        background-color: rgba(0, 0, 0, 0.5);
        color: white;
        padding: 10px;
        border-radius: 50%;
        cursor: pointer;
        user-select: none;
    }

    .prev {
        left: 10px;
    }

    .next {
        right: 10px;
    }

    .prev:hover,
    .next:hover {
        background-color: rgba(0, 0, 0, 0.7);
    }


    .card {
        background-color: #aa969a;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        max-width: 700px;
        margin: 20px auto;
        text-align: center;
        transition: transform 0.2s ease-in-out;
    }

    .card h2 {
        font-size: 24px;
        margin-bottom: 10px;
    }

    .card p {
        font-size: 16px;
        color: #ffffff;
        margin-bottom: 20px;
    }

    .btn-card {
        background-color: #464444;
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .btn-card:hover {
        background-color: #b50e33;
    }

    .card:hover {
        transform: translateY(-10px);
    }

    footer {
        background-color: #dc143c;
        color: #fff;
        text-align: center;
        padding: 10px 0;
        position: relative;
        /* Cambiado a relative para que no esté fijo */
        width: 100%;
    }

    .logo {
        display: flex;
        align-items: center;
        font-size: 24px;
        font-weight: bold;
    }

    .logo-img {
        width: 40px;
        height: 40px;
        margin-right: 10px;
        border-radius: 50%;
    }

    .card2 {
        background-color: #ffffff;
        border: 1px solid #ddd;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 16px;
        max-width: 600px;
        margin: 20px auto;
    }

    .card-content2 {
        font-family: Arial, sans-serif;
        text-align: justify;
        font-size: 16px;
        line-height: 1.5;
        color: #333;
    }

    .card3 {
        background-color: #ffffff;
        border: 1px solid #ddd;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 16px;
        max-width: 900px;
        margin: 20px auto;
    }

    .card-content3 {
        font-family: Arial, sans-serif;
        text-align: justify;
        font-size: 16px;
        line-height: 1.5;
        color: #333;
    }

    /* Media Queries para Responsividad */
    @media (max-width: 768px) {
        .nav-links {
            flex-direction: column;
            /* Coloca los enlaces en columna en pantallas pequeñas */
            align-items: center;
            /* Centra los enlaces */
            margin-top: 10px;
            /* Margen superior para separación */
        }

        .nav-links li {
            margin-left: 0;
            /* Elimina margen izquierdo en pantallas pequeñas */
            margin-bottom: 10px;
            /* Añade separación entre enlaces */
        }

        .carrusel-container {
            height: 300px;
            /* Ajusta la altura del carrusel en pantallas pequeñas */
        }

        .vista h1 {
            font-size: 24px;
            /* Tamaño de fuente más pequeño para encabezados */
        }

        .vista p {
            font-size: 16px;
            /* Tamaño de fuente más pequeño para párrafos */
        }

        .card h2 {
            font-size: 20px;
            /* Tamaño de fuente más pequeño para los encabezados de la card */
        }

        .card p {
            font-size: 14px;
            /* Tamaño de fuente más pequeño para los párrafos de la card */
        }
    }
</style>

<body>
    <header>
        <nav class="navbar">
            <div class="logo">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Kotlin_Icon.png/1200px-Kotlin_Icon.png"
                    alt="Logo" class="logo-img">
                Jobs4UesStudents
            </div>
            <ul class="nav-links">
                <li><a href="#" onclick="mostrarVista('inicio')">Inicio</a></li>
                <li><a href="#" onclick="mostrarVista('servicios')">Términos y Condiciones</a></li>
                <li><a href="#" onclick="mostrarVista('contacto')">¿Quienes Somos?</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <!-- Vista de Inicio -->
        <section id="inicio" class="vista">
            <h1>¡¡¡ Bienvenido a Jobs4UesStudents App !!!</h1>
            <div class="logo"></div>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Kotlin_Icon.png/1200px-Kotlin_Icon.png"
                alt="Logo" class="logo-img">
            </div>
            <br>
            <br>
            <p>Acá encontrarás información sobre nuestra App creada para tí.</p>

            <!-- Carrusel de Imágenes (solo en Inicio) -->
            <section class="carrusel-container">
                <div class="carrusel">
                    <div class="slide active">
                        <img src="https://via.placeholder.com/300x600/FF5733/FFFFFF?text=Imagen+1" alt="Imagen 1">
                    </div>
                    <div class="slide active">
                        <img src="https://via.placeholder.com/300x600/33FF57/FFFFFF?text=Imagen+2" alt="Imagen 2">
                    </div>
                    <div class="slide active">
                        <img src="https://via.placeholder.com/300x600/3357FF/FFFFFF?text=Imagen+3" alt="Imagen 3">
                    </div>
                    <div class="slide">
                        <img src="https://via.placeholder.com/300x600/FF33A5/FFFFFF?text=Imagen+4" alt="Imagen 4">
                    </div>
                    <div class="slide">
                        <img src="https://via.placeholder.com/300x600/FFC300/FFFFFF?text=Imagen+5" alt="Imagen 5">
                    </div>
                    <div class="slide">
                        <img src="https://via.placeholder.com/300x600/DAF7A6/000000?text=Imagen+6" alt="Imagen 6">
                    </div>
                </div>
                <a class="prev" onclick="moverCarrusel(-1)">&#10094;</a>
                <a class="next" onclick="moverCarrusel(1)">&#10095;</a>
            </section>

            <hr>
            <br>

            <section>
                <div class="card">
                    <h2>Información sobre la App</h2>
                    <p>Aqui encontrarás la info sobre la app.</p>
                    <button class="btn-card">Leer más</button>
                </div>

            </section>

            <hr>
            <br>

        </section>

        <!-- Vista de Servicios -->
        <section id="servicios" class="vista" style="display: none;">
            <h1>Términos y Condiciones</h1>
            <div class="card3">
                <div class="card-content3">
                    <p class="terms-conditions">
                        Por favor, lea estos términos y condiciones antes de utilizar nuestro servicio.
                        <br>
                        <br>
                        <b class="v1">1. Aceptación de los Términos:</b> Al utilizar nuestro servicio, acepta estar
                        legalmente
                        obligado por estos términos y condiciones y nuestra Política de Privacidad.
                        <br>
                        <br>
                        <b class="v1">2. Tener :</b> Tener 18 años cumplidos o más.
                        <br>
                        <br>
                        <b class="v1">3. Uso Adecuado:</b> Se compromete a utilizar nuestro servicio solo con fines
                        legales
                        y de
                        acuerdo con estos términos y condiciones.
                        <br>
                        <br>
                        <b class="v1">4. Privacidad:</b> Su información personal se recopila y utiliza de acuerdo con
                        nuestra
                        Política de Privacidad.
                        <br>
                        <br>
                        <b class="v1">5. Modificaciones de los Términos:</b> Nos reservamos el derecho de modificar
                        estos
                        términos en cualquier momento.
                        <br>
                        <br>
                        <b class="v1">6. Limitación de Responsabilidad:</b> No seremos responsables de ningún daño
                        directo,
                        indirecto, incidental, especial, consecuente o ejemplar que resulte del uso o la imposibilidad
                        de
                        uso
                        del
                        servicio.
                        <br>
                        <br>
                        <b class="v1">7. Cancelación y Terminación:</b> Nos reservamos el derecho de cancelar o
                        suspender su
                        acceso al servicio en cualquier momento, sin previo aviso, por cualquier motivo, incluyendo, sin
                        limitación, el
                        incumplimiento de estos términos y condiciones.
                        <br>
                        <br>
                        <b class="v1">8. Uso de la Cámara del Dispositivo:</b> Al utilizar nuestro servicio, puede
                        permitirnos
                        acceder a la cámara de su dispositivo móvil. Cualquier imagen o video capturado a través de
                        nuestra
                        aplicación será
                        recopilado y utilizado de acuerdo con nuestra Política de Privacidad. Usted es responsable de
                        garantizar
                        que el uso de la cámara no infrinja los derechos de privacidad de terceros.
                        <br>
                        <br>
                        <b class="v1">9. Consentimiento para el Uso de Datos de la Cámara:</b> Al habilitar el acceso a
                        la
                        cámara de su dispositivo, usted consiente la recopilación, almacenamiento y uso de imágenes y
                        videos
                        según se
                        describe en nuestra Política de Privacidad. Puede desactivar el acceso a la cámara en cualquier
                        momento
                        a través de la configuración de su dispositivo.
                        <br>
                        <br>
                        Al utilizar nuestro servicio, acepta estos términos y condiciones en su totalidad. Si no está de
                        acuerdo
                        con ellos, no utilice nuestro servicio.
                        <br>
                        <br>
                    </p>
                </div>
            </div>
            <br>
            <br>
        </section>

        <!-- Vista de Contacto -->
        <section id="contacto" class="vista" style="display: none;">
            <h1>¿Quienes Somos?</h1>
            <div class="card2">
                <div class="card-content2">
                    <p>Somos un grupo de estudiantes entusiastas y comprometidos que han decidido
                        unir fuerzas para desarrollar una innovadora aplicación de Android utilizando
                        Kotlin. Nuestra misión es crear una bolsa de trabajo universitaria que sirva como
                        un puente entre los estudiantes y las oportunidades laborales que mejor se adapten
                        a sus necesidades y aspiraciones profesionales.
                    </p>
                    <br>

                    <p>
                        Reconocemos los desafíos que enfrentan
                        los jóvenes al ingresar al mundo laboral, donde la búsqueda de empleo puede ser un proceso
                        complicado y abrumador. Por eso, hemos diseñado nuestra app con un enfoque intuitivo y
                        accesible,
                        permitiendo a los usuarios explorar una variedad de ofertas laborales
                        y postularse de manera sencilla y rápida.
                    </p>
                </div>
            </div>

        </section>
    </main>

    <footer>
        <p>&copy; 2024 Jobs4UesStudents. Todos los derechos reservados.</p>
    </footer>

    <script>
        let slideIndex = 0;

        // Función para mostrar la vista seleccionada
        function mostrarVista(vista) {
            // Guardamos la vista seleccionada en localStorage
            localStorage.setItem('vistaActual', vista);

            // Ocultamos todas las vistas
            document.querySelectorAll('.vista').forEach(function (section) {
                section.style.display = 'none';
            });
            // Mostramos la vista seleccionada
            document.getElementById(vista).style.display = 'block';
        }

        // Función para mostrar el slide activo del carrusel
        function mostrarSlides() {
            const slides = document.querySelectorAll('.slide');
            const totalSlides = slides.length;

            // Calcula la posición del carrusel
            const offset = (slideIndex * 300); // 300 es el ancho de cada slide
            document.querySelector('.carrusel').style.transform = `translateX(-${offset}px)`;
        }

        // Función para mover el carrusel con las flechas
        function moverCarrusel(n) {
            const slides = document.querySelectorAll('.slide');
            const totalSlides = slides.length;

            slideIndex += n;

            // Asegúrate de que el índice esté dentro del rango
            if (slideIndex < 0) {
                slideIndex = 0;
            }
            if (slideIndex > totalSlides - 3) { // 3 es el número de imágenes visibles
                slideIndex = totalSlides - 3;
            }

            mostrarSlides();
        }

        // Inicializa el carrusel
        mostrarSlides();

        // Al cargar la página, verificamos la vista que se quedó en localStorage
        window.onload = function () {
            const vistaGuardada = localStorage.getItem('vistaActual');
            if (vistaGuardada) {
                mostrarVista(vistaGuardada);
            } else {
                mostrarVista('inicio'); // Si no hay vista guardada, mostramos "Inicio" por defecto
            }
        };
    </script>
</body>

</html>
